# Generated by Django 5.2.7 on 2026-01-06 03:25

import battery_record.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatteryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('condition', models.CharField(choices=[('OK', 'OK (Pass)'), ('NG', 'NG (Reject)'), ('RECHECK', 'Re-Check')], default='OK', max_length=20)),
                ('voltage', models.CharField(blank=True, help_text='Contoh: 12.4 V', max_length=10, null=True)),
                ('screenshot', models.ImageField(upload_to=battery_record.models.battery_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Battery QC Record',
                'ordering': ['-created_at'],
            },
        ),
    ]
