# Generated by Django 5.2.7 on 2026-01-07 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traceability', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('current_status', models.CharField(choices=[('PENDING', 'Pending QC'), ('OK', 'OK (Ready Stock)'), ('NG', 'Not Good (Reject)'), ('USED', 'Used (Installed)'), ('SCRAPPED', 'Scrapped')], db_index=True, default='PENDING', max_length=20)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='traceability.partmaster')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('part_master', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='QCInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qc_result_data', models.JSONField(default=dict)),
                ('judge_decision', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('inspection_date', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='qc.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='QCTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text='Key JSON (ex: voltage)', max_length=50)),
                ('field_label', models.CharField(help_text='Label di UI', max_length=100)),
                ('field_type', models.CharField(choices=[('NUMBER', 'Angka'), ('TEXT', 'Teks'), ('BOOLEAN', 'OK/NG Check'), ('IMAGE', 'Foto/Upload')], max_length=20)),
                ('min_val', models.FloatField(blank=True, null=True)),
                ('max_val', models.FloatField(blank=True, null=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('part_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qc_templates', to='traceability.partmaster')),
            ],
        ),
    ]
