# Generated by Django 5.2.7 on 2026-01-06 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_productcolor_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('code', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='VinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serial_number', models.CharField(max_length=6)),
                ('full_vin', models.CharField(db_index=True, max_length=17, unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productcolor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.producttype')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productvariant')),
                ('production_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vin_record.yearcode')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VinPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wmi_vds', models.CharField(help_text='Masukan 8 Karakter pertama (WMI + VDS)', max_length=8)),
                ('plant_code', models.CharField(help_text='Kode Pabrik (1 Digit)', max_length=1)),
                ('static_ninth_digit', models.CharField(default='0', help_text='Dipakai jika Check Digit dimatikan.', max_length=1)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vin_prefixes', to='product.producttype')),
                ('year_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefixes', to='vin_record.yearcode')),
            ],
            options={
                'unique_together': {('product_type', 'year_code')},
            },
        ),
    ]
