# Generated by Django 5.2.7 on 2026-01-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_producttype_is_vin_trace_and_more'),
        ('vin_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vinrecord',
            options={'ordering': ['serial_number']},
        ),
        migrations.AddField(
            model_name='vinrecord',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vinrecord',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('USED', 'Used / Assembled'), ('SCRAPPED', 'Scrapped')], db_index=True, default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='vinrecord',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='vinrecord',
            unique_together={('product_type', 'production_year', 'serial_number')},
        ),
    ]
