# Generated by Django 5.2.7 on 2026-01-07 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_alter_productcolor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Kode Rule Internal', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RuleSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('segment_type', models.CharField(choices=[('STATIC', 'Karakter Tetap (Ex: BAT)'), ('DIGIT', 'Angka (0-9)'), ('CHAR', 'Huruf (A-Z)'), ('ALPHANUM', 'Huruf & Angka'), ('YEAR', 'Tahun (2 Digit)'), ('MONTH', 'Bulan (2 Digit)')], max_length=20)),
                ('start_index', models.IntegerField(blank=True, help_text='Posisi mulai (Index 1). Jika kosong, akan lanjut dari segmen sebelumnya.', null=True)),
                ('length', models.PositiveIntegerField(default=1, help_text='Jumlah karakter/digit')),
                ('static_value', models.CharField(blank=True, help_text='Isi jika tipe STATIC', max_length=50, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='traceability.serialrule')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PartMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('part_name', models.CharField(max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('validation_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traceability.serialrule')),
            ],
        ),
        migrations.CreateModel(
            name='TraceabilityVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.CharField(help_text='Ex: REV-001 or V1.0', max_length=50)),
                ('valid_from', models.DateField(help_text='Tanggal mulai berlaku')),
                ('is_active', models.BooleanField(default=True, help_text='Versi yang sedang digunakan saat ini')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_versions', to='product.producttype')),
            ],
            options={
                'verbose_name': 'Traceability Version / BOM Header',
                'unique_together': {('product_type', 'version_code')},
            },
        ),
        migrations.CreateModel(
            name='TraceabilityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('part_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traceability.partmaster')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='traceability.traceabilityversion')),
            ],
            options={
                'unique_together': {('version', 'part_master')},
            },
        ),
    ]
