# Generated by Django 5.2.7 on 2026-01-06 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama Aturan (ex: Rule Baterai 2024)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Kode Unik Rule', max_length=50, unique=True)),
                ('prefix', models.CharField(help_text='Awalan (ex: BAT, ECU)', max_length=20)),
                ('reset_period', models.CharField(choices=[('NEVER', 'Never Reset (Terus bertambah)'), ('YEARLY', 'Reset Tiap Tahun'), ('MONTHLY', 'Reset Tiap Bulan')], default='NEVER', max_length=10)),
                ('digit_length', models.IntegerField(default=4, help_text='Jumlah digit urut (ex: 4 digit = 0001)')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(help_text='SKU / Kode Part Internal', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('numbering_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traceability.numberingrule')),
            ],
        ),
        migrations.CreateModel(
            name='PartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('GOOD', 'Good / OK'), ('NG', 'No Good / Reject'), ('INSTALLED', 'Installed on Unit'), ('SCRAPPED', 'Scrapped')], default='GOOD', max_length=20)),
                ('installed_vin', models.CharField(blank=True, db_index=True, max_length=17, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='traceability.partmaster')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('last_number', models.IntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='traceability.numberingrule')),
            ],
            options={
                'unique_together': {('rule', 'year', 'month')},
            },
        ),
    ]
