# Generated by Django 5.2.9 on 2026-01-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_producttype_scheduling_policy_and_more'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partmaster',
            name='compatible_product_types',
            field=models.ManyToManyField(blank=True, help_text='Pilih Tipe Produk yang menggunakan part ini.', related_name='compatible_parts', to='product.producttype'),
        ),
    ]
