# Generated by Django 5.2.7 on 2026-01-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traceabilityversion',
            options={'ordering': ['-valid_from'], 'verbose_name': 'Traceability Version / BOM Header'},
        ),
    ]
