# Generated by Django 5.2.7 on 2026-01-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['name']},
        ),
    ]
