# Generated by Django 5.2.7 on 2026-01-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productcolor_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='is_vin_trace',
        ),
        migrations.AddField(
            model_name='producttype',
            name='tracking_mode',
            field=models.CharField(choices=[('VIN', 'By VIN (Strict)'), ('INTERNAL_ID', 'By System ID'), ('BATCH', 'By Qty Counter')], default='VIN', help_text='Menentukan cara tracking di lantai produksi', max_length=20),
        ),
    ]
