# Generated by Django 5.2.9 on 2026-01-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_producttype_is_vin_trace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='scheduling_policy',
            field=models.CharField(choices=[('DAILY_RESET', 'Daily Reset (Handover Harian)'), ('CONTINUOUS', 'Continuous (Project Long-Running)')], default='DAILY_RESET', help_text='Menentukan apakah SPK harus ditutup harian (Handover) atau berjalan terus sampai target selesai.', max_length=20),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='tracking_mode',
            field=models.CharField(choices=[('VIN', 'By VIN (Strict)'), ('INTERNAL_ID', 'By System ID'), ('BATCH', 'By Qty Counter')], default='VIN', help_text='Menentukan apakah sistem harus men-generate Serial Number unik per unit atau hanya menghitung jumlah.', max_length=20),
        ),
    ]
