# Generated by Django 5.2.7 on 2026-01-09 02:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_remove_producttype_is_vin_trace_and_more'),
        ('traceability', '0001_initial'),
        ('vin_record', '0002_alter_vinrecord_options_vinrecord_booking_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('default_sequence', models.PositiveIntegerField(default=1)),
                ('is_finish_point', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['work_center', 'default_sequence'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_continuous', models.BooleanField(default=True, help_text='True=Line Ban Berjalan, False=Custom Bay')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=50, unique=True)),
                ('target_qty', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('realized_qty', models.PositiveIntegerField(default=0)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('tracking_mode_snapshot', models.CharField(choices=[('VIN', 'By VIN (Strict)'), ('INTERNAL_ID', 'By System ID'), ('BATCH', 'By Qty Counter')], max_length=20)),
                ('target_total_qty', models.PositiveIntegerField()),
                ('carried_over_wip_qty', models.PositiveIntegerField(default=0)),
                ('new_material_qty', models.PositiveIntegerField(default=0)),
                ('actual_finish_qty', models.PositiveIntegerField(default=0)),
                ('actual_reject_qty', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('CLOSED', 'Closed/Handover'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_orders', to='production.productionplan')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='product.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('WIP', 'In Progress'), ('PAUSED', 'Line Off / Kendala'), ('FINISH_PROD', 'Finish Production'), ('SCRAPPED', 'Scrapped')], default='WIP', max_length=20)),
                ('is_paused', models.BooleanField(default=False)),
                ('pause_reason', models.TextField(blank=True, null=True)),
                ('origin_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='production.productionorder')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productvariant')),
                ('vin_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vin_record.vinrecord')),
                ('current_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='production.station')),
            ],
            options={
                'unique_together': {('origin_order', 'internal_id')},
            },
        ),
        migrations.CreateModel(
            name='PartInstallationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number_scanned', models.CharField(max_length=100)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('installed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part_master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traceability.partmaster')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_parts', to='production.productionunit')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='production.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('result_status', models.CharField(default='PROCESS', max_length=20)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.station')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='production.productionunit')),
            ],
        ),
        migrations.AddField(
            model_name='station',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='production.workcenter'),
        ),
        migrations.CreateModel(
            name='RouteStationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('progress_percentage', models.FloatField(help_text='Akumulasi Progres (0-100%) jika lolos station ini', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='production.productionroute')),
                ('traceability_triggers', models.ManyToManyField(blank=True, help_text='Part yang wajib discan di station ini', to='traceability.traceabilityrequirement')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.station')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('route', 'station')},
            },
        ),
        migrations.CreateModel(
            name='StationBatchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_wip_qty', models.PositiveIntegerField(default=0)),
                ('input_qty', models.PositiveIntegerField(default=0)),
                ('output_good_qty', models.PositiveIntegerField(default=0)),
                ('output_reject_qty', models.PositiveIntegerField(default=0)),
                ('current_wip_qty', models.PositiveIntegerField(default=0)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_records', to='production.productionorder')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.station')),
            ],
            options={
                'unique_together': {('production_order', 'station')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('work_center', 'code')},
        ),
    ]
