# Generated by Django 5.2.7 on 2026-01-09 08:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='tracking_mode_snapshot',
            field=models.CharField(blank=True, choices=[('VIN', 'By VIN (Strict)'), ('INTERNAL_ID', 'By System ID'), ('BATCH', 'By Qty Counter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productionunit',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='production.station'),
        ),
        migrations.AlterField(
            model_name='routestationconfig',
            name='progress_percentage',
            field=models.FloatField(default=0, help_text='Akumulasi Progres (0-100%) jika lolos station ini', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='routestationconfig',
            name='traceability_triggers',
            field=models.ManyToManyField(blank=True, help_text='Part yang WAJIB discan di station ini sebelum unit boleh PASS.', related_name='route_configs', to='traceability.partmaster'),
        ),
        migrations.AlterField(
            model_name='station',
            name='is_finish_point',
            field=models.BooleanField(default=False, help_text='Jika True, unit yang lewat sini dianggap Selesai (Output).'),
        ),
        migrations.AlterField(
            model_name='stationactivitylog',
            name='result_status',
            field=models.CharField(choices=[('PROCESS', 'Processing'), ('PASS', 'OK'), ('REJECT', 'NG'), ('PAUSE', 'Paused')], default='PROCESS', max_length=20),
        ),
    ]
