# Generated by Django 5.2.7 on 2026-01-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_producttype_is_vin_trace_and_more'),
        ('production', '0002_alter_productionorder_tracking_mode_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='color',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='production_plans', to='product.productcolor'),
            preserve_default=False,
        ),
    ]
