# Generated by Django 5.2.7 on 2026-01-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionplan_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='current_wip_qty',
            field=models.PositiveIntegerField(default=0, help_text='Jumlah unit yang sedang berjalan (WIP)'),
        ),
    ]
