# Generated by Django 5.2.9 on 2026-01-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_productionorder_current_wip_qty'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestationconfig',
            options={'ordering': ['route', 'sequence']},
        ),
        migrations.AddField(
            model_name='routestationconfig',
            name='job_description',
            field=models.TextField(blank=True, help_text='Instruksi kerja untuk operator'),
        ),
        migrations.AddField(
            model_name='routestationconfig',
            name='job_weight',
            field=models.FloatField(default=0, help_text='Bobot pekerjaan dalam % (Total harus 100)'),
        ),
        migrations.AlterField(
            model_name='routestationconfig',
            name='progress_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='routestationconfig',
            name='sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='routestationconfig',
            name='traceability_triggers',
            field=models.ManyToManyField(blank=True, related_name='route_configs', to='traceability.partmaster'),
        ),
    ]
