# Generated by Django 5.2.9 on 2026-01-10 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_routestationconfig_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionunit',
            name='origin_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='production.productionorder'),
        ),
        migrations.AlterField(
            model_name='stationbatchrecord',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_records', to='production.productionorder'),
        ),
    ]
