# Generated by Django 5.2.9 on 2026-01-10 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_productionunit_origin_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
