# Generated by Django 5.2.9 on 2026-01-12 05:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_alter_productionorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyStationOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('qty_good', models.PositiveIntegerField(default=0)),
                ('qty_reject', models.PositiveIntegerField(default=0)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_outputs', to='production.productionorder')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.station')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('production_order', 'station', 'date')},
            },
        ),
    ]
