# Generated by Django 5.2.9 on 2026-01-12 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_productionorder_closed_at_dailystationoutput'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionunit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('RELEASED', 'Released'), ('CLOSED', 'Closed/Handover'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionunit',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('WIP', 'In Progress'), ('PAUSED', 'Line Off / Kendala'), ('FINISH_PROD', 'Finish Production'), ('SCRAPPED', 'Scrapped')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='stationactivitylog',
            name='result_status',
            field=models.CharField(choices=[('PROCESS', 'Processing'), ('PASS', 'OK'), ('REJECT', 'NG'), ('PAUSE', 'Paused'), ('START_MANUAL', 'Force Start by Supervisor')], default='PROCESS', max_length=30),
        ),
    ]
