# Generated by Django 5.2.7 on 2025-12-17 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_printtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nama Modul (Contoh: VIN Record)', max_length=100)),
                ('code', models.SlugField(help_text='Kode unik (Contoh: vin_record)', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='printtemplate',
            name='is_active',
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='height_mm',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='module_scope',
            field=models.CharField(default='vin_record', max_length=50),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='width_mm',
            field=models.FloatField(default=100),
        ),
        migrations.CreateModel(
            name='LabelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.CharField(help_text='Contoh: {{ full_vin }}', max_length=100)),
                ('field_label', models.CharField(help_text='Contoh: No. Rangka Lengkap', max_length=100)),
                ('dummy_data', models.CharField(blank=True, help_text='Contoh data untuk preview (MH1RW...)', max_length=100)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.labelmodule')),
            ],
        ),
    ]
